Repository YHU-team18/Read-files-and-learn-words, pull requests merged in 2022-06, with the labels that each got.

#18 for dev done#8
  README.md
  src/dev.sh
  src/for_dev_CR.py
  src/words/admin.py
  start.sh
Labels: bug, enhancement

#21 Create LICENCE
  LICENCE
Labels: documentation

#17 d&dでpdf読み込み機能実装
  src/static/css/style.css
  src/static/js/style.js
  src/templates/base.html
  src/templates/input_pdf.html
  src/words/views.py
  src/yhu_t18/settings.py
Labels: documentation

#20 BoW#6
  LICENCE
  docker_dir/requirements.txt
  src/PDFtoBow/PDFtoBoW.py
  src/PDFtoBow/README.md
  src/PDFtoBow/sample1.pdf
  src/PDFtoBow/sample2.pdf
  src/PDFtoBow/test.py
  src/PDFtoBow/test_BoW1.json
  src/PDFtoBow/test_BoW2.json
  src/PDFtoBow/test_result.txt
  src/PDFtoBow/words_by_frequency.txt
  src/readme.md
Labels: enhancement

#22 [JS to Python]JSからD&Dされたファイルを含んだPOSTを行いPythonで受け取る
  src/static/js/style.js
  src/templates/input_pdf.html
  src/templates/submit_pdf.html
  src/tmp/.gitkeep
  src/words/urls.py
  src/words/views.py
  src/yhu_t18/settings.py
Labels: enhancement

#28 get_BoWが{'単語': 頻度}, {'単語': '辞書のエントリー'}の二つを返すように変更
  LICENCE
  src/PDFtoBow/PDFtoBoW.py
  src/PDFtoBow/README.md
  src/PDFtoBow/sample1_frequency.json
  src/PDFtoBow/sample1_meaning.json
  src/PDFtoBow/sample2_frequency.json
  src/PDFtoBow/sample2_meaning.json
  src/PDFtoBow/test.py
  src/PDFtoBow/test_BoW1.json
  src/PDFtoBow/test_BoW2.json
  src/PDFtoBow/test_result.txt
Labels: enhancement
